[package]
name = "osm-tag-csv-history"
version = "0.2.0"
authors = ["Rory McCann <rory@technomancy.org>"]
edition = "2018"
license = "AGPL-3.0+"
repository = "https://git.sr.ht/~ebel/osm-tag-csv-history"
description = "Use CSV tools to see who's mapping what in OpenStreetMap."
keywords = ["openstreetmap", "osm"]

[dependencies]
csv = "1.1.1"
anyhow = "1.0.26"
osmio = "0.2.0"
log = "0.4.0"
env_logger = "0.7.1"
clap = "2.33.0"
flate2 = "1.0.13"
