[package]
name = "osm-tag-csv-history"
version = "0.1.0"
authors = ["Rory McCann <rory@technomancy.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.1"
anyhow = "1.0.26"
osmio = { path = "/home/rory/code/rust/osmio/" }
log = "0.4.0"
env_logger = "0.7.1"
clap = "2.33.0"
flate2 = "1.0.13"
